Output – MHDTurbulence
Output Subroutine
25 statements
Source File
subroutine Output(is_final)
Uses
basicmod
mpimod
config
mpiiomod
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: is_final
Calls
Source Code
subroutine Output(is_final)
  use config, only: asciiout
  use mpimod
  use basicmod
  use mpiiomod
  implicit none
  logical, intent(in):: is_final
  real(8),save:: tout
  data tout / 0.0d0 /
  integer,save:: nout
  data nout / 1 /
  logical, save:: is_inited
  data is_inited /.false./
  if(time .lt. tout+dtout .and. .not. is_final) return
!$omp target update from(d,v1,v2,v3)
!$omp target update from(p,ei,cs)
!$omp target update from(b1,b2,b3,bp)
!$omp target update from(gp)
!$omp target update from(Xcomp)
  call MPI_IO_Pack(nout)
  call MPI_IO_Write(nout)
  if(myid_w==0) call WriteXDMF(time,nout)
  if(asciiout) then
     call ASC_WRITE(nout)
  endif
  if(myid_w==0) print *, "output:",nout,time
  nout=nout+1
  tout=time
  return
  !         write(6,*) "bpf2",nflux2(mbps,i,j,k)
end subroutine Output
Call graph
output calls asc_write, mpi_io_pack, mpi_io_write, writexdmf
mpi_io_pack calls makedirs
mpi_io_write calls mpi_comm_split, mpi_file_close, mpi_file_open, mpi_file_set_view, mpi_file_write_all, mpi_type_commit, mpi_type_create_subarray