site_name: MHDTurbulence Guides
site_description: User-facing documentation for MHDTurbulence
site_url: https://cfcanaoj.github.io/MHDTurbulence/guide/
docs_dir: .
site_dir: ../.mkdocs-site/guide
use_directory_urls: false

theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Project Overview: README.md
  - Kelvin-Helmholtz Setup: KH.md

exclude_docs: |
  *.md~
  custom.css
  Doxyfile-*
  doxygen-*
  ford-*
  site/
